### PR TITLE
Add pnpm-lock.yaml file

### PR DESCRIPTION
**Pull request by arpitjalan**
When deploying on fly the build process is complaining about missing `pnpm-lock.yaml` file

```
Error: failed to fetch an image or build from source: error building: failed to solve: failed to compute cache key: "/pnpm-lock.yaml" not found: not found
```

### CODE REVIEW

**Comment by michael** [comment]
Hey! Is there any particular reason you use pnpm over standard npm for deployment?

**Comment by arpitjalan** [comment]
Hey @michael,

I do prefer pnpm over npm because of the better performance and [less disk space usage](https://pnpm.io/pnpm-vs-npm). But the reason for this PR is because the fly generated Dockerfile in my case was installing pnpm even though I had not generated `pnpm-lock.yaml`.

I see [Fly checking for the lock files](https://github.com/fly-apps/dockerfile-node/blob/25a40dfe325004a5c8710b105a3d11ff08fe1c95/gdf.js#L463-L484) to get the packager but in my case I'm not sure why it detected pnpm.

Should we stick with standard npm instead of pnpm for PostOwl production deployment?

**Comment by michael** [comment]
Yeah I think pnpm is fine for local dev. With this project and similiar ones (Node + SQLite) we decided to always pick the most boring, least surprising tech stack and support only that.  Just so we make reproducing issues easier. We may want to switch the whole thing to Bun at some point, but I thin it's too early and Node with classic npm is the safe bet.

So yeah, would be interesting to find out why the Fly Docker generator assumes pnpm here?

**Comment by arpitjalan** [comment]
Sure, I agree with your point to stick with the stable/boring Node + npm stack for now until Bun matures enough for production.

I cloned a fresh PostOwl repo and tried Fly launch again, and this time the generated Dockerfile had npm as a dependency, so there must be something amiss with my dev repo that tricked Fly to think I was using pnpm (and I do use pnpm frequently for dev). So, looks like we're all good here.

**Comment by michael** [comment]
Ah yeah, the whole Fly.io deployment thing works off your local copy. The nice thing about it is doesn't depend on anything (like Git) but the bad thing is that when you deploy from different computers you may end up with different results, which could potentially break deployments. So we have to be careful here, and possibly research a bit how other people solve this multi-computer problems when working with Fly.

@keybits I think this is another reason why our "hosted deployment solution" makes a ton of sense. :)

**Pull request closed without merging**
